http:
  port: 8080

apiEndpoints:
  inventario:
    path: /inventario/*
    target: http://inventario:3001      # nombre del servicio Docker + puerto
  despacho:
    path: /despacho/*
    target: http://despacho:3002
  reporte:
    path: /reporte/*
    target: http://reporte:3003
  seguridad:
    path: /seguridad/*
    target: http://seguridad:3004
  recepcion:
    path: /recepcion/*
    target: http://recepcion:3005

serviceEndpoints:
  inventario:
    url: http://inventario:3001
  despacho:
    url: http://despacho:3002
  reporte:
    url: http://reporte:3003
  seguridad:
    url: http://seguridad:3004
  recepcion:
    url: http://recepcion:3005
